detector: ml
model_type: firemlp
checkpoint: checkpoint/fire_detector_mlp_best.pt
threshold: 0.5
training:
  loss: error-rate
  layers:
  - 64
  - 32
  learning_rate: 0.01
  epochs: 100
  importance_weights:
    gt: 10
    fire: 5
    other: 1
metrics:
  error_rate: 0.030877812086457873
  precision: 0.976056338028169
  recall: 0.9934936038817821
  TP: 9009
  FP: 221
  FN: 59
  TN: 519558
